# Generated by Django 2.1.5 on 2019-01-05 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 14, 38, 57, 124431, tzinfo=utc)),
        ),
    ]
